name: Fejlrapport
description: Indsendelse af fejl som er identificeret i forbindelse med brug af løsningen
title: "[Bug]: "
body:
  - type: input
    id: contact
    attributes:
      label: Kontaktoplysninger
      description: Hvordan kan vi kontakte dig hvis der er behov for yderligere oplysninger?
      placeholder: ex. email@example.com
    validations:
      required: false
