name: Fejlrapport
description: Indsendelse af fejl, som er identificeret i forbindelse med brug af løsningen
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: Tak, for du tager dig tid til at udfylde fejlrapporten!
  - type: input
    id: contact
    attributes:
      label: Kontaktoplysninger
      description: Hvordan kan vi kontakte dig, hvis der er behov for yderligere oplysninger?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: where-happened
    attributes:
      label: Hvor skete der?
      description: Hvor i løsningen problemet opstod?
      placeholder: Fortæl hvor der skete!
      value: "På login siden da...!"
    validations:
      required: true
  - type: textarea
      id: what-happened
      attributes:
        label: Hvad skete der?
        description: Hvad skete der da problemet opstod og hvad var det forventede?
        placeholder: Fortæl hvad der skete!
        value: "En fejl opstod da...!"
      validations:
        required: true
      - type: dropdown
        id: version
        attributes:
          label: Version
          description: Hvilken version af løsningen er benyttet?
          options:
            - 1.0.2 (Default)
            - 1.0.3 (Edge)
        validations:
          required: true
      - type: dropdown
        id: platform
        attributes:
          label: Hvilken platfrom blev benyttet, da problemet opstod?
          options:
            - PC
            - Mac
            - Andet
        validations:
          required: true
  - type: dropdown
      id: browsers
      attributes:
        label: Hvilken browser blev benyttet, da problemet opstod?
        multiple: true
        options:
          - Firefox
          - Chrome
          - Safari
          - Microsoft Edge
  - type: dropdown
      id: severity
      attributes:
        label: Hvilken grad af alvorlighed har problemet?
        options:
          - Blokerende
          - Kritisk
          - Høj
          - Lav
          - Ej krtisk
          - Ny eller forbedrende
  - type: textarea
    id: information
    attributes:
      label: Relevant information
      description: Venligst tilføj relevant information, som har med problemet at gøre
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Vilkår
      description: Ved at indsende dette problem, accepterer du at følge vilkårene for løsningen
      options:
        - label: Jeg accepterer at følge løsningens vilkår
          required: true
